"""Add data field to File model

Revision ID: 267213b14efd
Revises: fcb22cbfa6f1
Create Date: 2022-04-18 13:54:54.119493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '267213b14efd'
down_revision = 'fcb22cbfa6f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('data', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'data')
    # ### end Alembic commands ###
