"""Add user role column

Revision ID: 700f77082124
Revises: 
Create Date: 2022-04-06 02:33:50.006776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '700f77082124'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
