"""Add Foreign key

Revision ID: be9885c7ce2b
Revises: 700f77082124
Create Date: 2022-04-14 09:39:26.178366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be9885c7ce2b'
down_revision = '700f77082124'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('file', sa.String(length=100), nullable=True))
    op.add_column('files', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint('files_email_key', 'files', type_='unique')
    op.create_foreign_key(None, 'files', 'users', ['user_id'], ['id'])
    op.drop_column('files', 'password')
    op.drop_column('files', 'name')
    op.drop_column('files', 'email')
    op.drop_column('files', 'role')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('role', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.add_column('files', sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('files', sa.Column('name', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.add_column('files', sa.Column('password', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'files', type_='foreignkey')
    op.create_unique_constraint('files_email_key', 'files', ['email'])
    op.drop_column('files', 'user_id')
    op.drop_column('files', 'file')
    # ### end Alembic commands ###
